### ISSUE TITLE
Github Api analyze

### ISSUE THREAD

**Issue by lucax88x** [lucax88x/nvim-awesome#1]
We want to see number of stars so we can sort.
We want to see the code type, so we can also filter by Lua or vim script.

There is a rate limit that we need to discuss. 

Plugins data will be statically available.

what about a 1 hour server cache for each plugin? Should it be enough? Better ideas?

**Comment by cuducos** [comment]
I don't know much of the JS world and about our infrastructure. Ideal scenario would be a task queue that asynchronously gets this info (stars and language) and saves. I am pretty much familiar with stuff like that in Python or Go. Is that possible with the current servers?
