### ISSUE TITLE
Demo Website

### ISSUE THREAD

**Issue by pidgeon777** [lucax88x/nvim-awesome#13]
Hello, from what I've understood, your goal is to create a website that lists the Github repositories of Neovim plugins.

If then, great idea!

It could be a successor of this website:

https://vimawesome.com/

My question is, is it possible to test this new website somewhat? For example, through a demo URL?

**Comment by lucax88x** [comment]
Yes man, it's already [live](https://nvim-awesome.vercel.app/)

**Comment by lucax88x** [comment]
Needless to say that's is very very very alpha stage.

**Comment by pidgeon777** [comment]
It already seems to be very good.

But will the repositories have to be added by hand, or will it automatically scan the existing ones?

**Comment by lucax88x** [comment]
I'm keeping it as simple as possible.

New plugins will need to be added by PR, so we can review and validate, in this folder of this repo, open to everyone.

https://github.com/lucax88x/nvim-awesome/tree/main/src/nvim-awesome.app/data/plugins
